theme: jekyll-theme-cayman
title: Simplify.Your(Tests).With(Fluent.Syntax)
description: Learn how to write short, simple and maintainable automated software tests with a fluent interface/builder pattern.
